// Generated by CoffeeScript 1.10.0
(function() {
  var assert, file;

  assert = require('assert');

  file = require('./../../build/coffee/test2.coffee');

  describe("Hello", function() {
    it("Output Privet", function() {
      return assert.equal(file.Hello(3), 'Privet!');
    });
    it("Hello admin!", function() {
      return assert.equal(file.Looking("Le0n1daS"), 'Hello Le0n1daS');
    });
    it("Fuck admin!", function() {
      return assert.equal(file.Looking("Le0n1das"), 'Fuck Off!');
    });
    it("Output Hello world without !", function() {
      return assert.equal(file.Hello(4), 'Hello world');
    });
    return it("Output Hello world!", function() {
      return assert.equal(file.Hello(5), "Hello world!");
    });
  });

}).call(this);
